### ISSUE TITLE
oracle: number type shown in scientific notation

### ISSUE THREAD

**Issue by helix84** [knq/usql#8] opened 2017-03-03 23:59 UTC
Example:
```
Column type:   NUMBER(22)
Value:         43856197
Shown by usql: 4.3856197e+07
```

**Comment by kenshaw** [comment] 2017-03-04 00:26
Yeah, there are a number of problems with some of the databases, and the types that are returned. The issue, primarily, is that the underlying drivers do not use the same types when converting their values to Go. I am going to retrofit the tool to better support these different types.

**Comment by kenshaw** [comment] 2017-03-04 00:43
I just tried a NUMBER(22) column type. The value was not displayed in scientific notation. Can you provide more information on the schema in use, and the actual query performed where you saw this output?

**Comment by kenshaw** [comment] 2017-03-06 14:44
I've tried with a number of different schemas, and cannot get this to reproduce. This might be an issue with the specific version of Oracle you're using, or the instantclient version, and the rana/ora driver. As it is, I can't really do much more without knowing more.

Could you pull the latest code and tell me if it is still a problem? Thanks!

**Comment by kenshaw** [comment] 2017-03-16 11:36
Closing this since there is no schema / column information provided, and can't test/fix this.

**Closed by kenshaw** 2017-03-16 11:36 UTC
